x <- -1:5
y=1-exp(-x)
plot(x) 
par(mfrow=c(3,6),oma=c(0,0,0,0),mar=c(3,3,3,1))
plot(x)
text(5,0,"Gráfica 1")
plot(y)
text(5,0,"Gráfica 2")
plot(x,y)
text(3,0,"Gráfica 3")
plot(x,y,pch=16)
text(3,0,"Gráfica 4")
plot(x,y,pch=16,xlab="eje de las n??s")
text(3,0,"Gráfica 5")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)")
text(3,0,"Gráfica 6")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1")
text(3,0,"Gráfica 7")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="pink")
text(3,0,"Gráfica 8")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue")
text(3,0,"Gráfica 9")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2)
text(3,0,"Gráfica 10")
abline(h=1)
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2)
text(3,0,"Gráfica 11")
abline(h=1,lty=2)
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2)
text(3,0,"Gráfica 12")
abline(h=1,lty=2,lwd=5)
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2)
text(3,0,"Gráfica 13")
abline(h=1,lty=2,lwd=5,col="red")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2,fg="purple",las="1")
text(3,0,"Gráfica 14")
abline(h=1,lty=2,lwd=5,col="red")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2,fg="purple",las="1",type="l")
text(3,0,"Gráfica 15")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2,fg="purple",las="1",type="p")
text(3,0,"Gráfica 16")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2,fg="purple",las="1",type="o")
text(3,0,"Gráfica 17")
abline(h=1,lty=2,lwd=5,col="red")
plot(x,y,pch=16,xlab="eje de las n??s",ylab="f(n)",main="Sucesión convergente a 1",col="blue",cex=2,fg="purple",las="1",type="o")
text(3,0,"Gráfica 18")
abline(h=1,lty=1,lwd=5,col="red")
plot(1:2, xaxs = "i")
plot(1:2)
