x <- -10:10
y <- x^3 
plot(x,y,type = 'l',col=1:21)
abline(h=0,v=0)
plot(x,y,type = 'p',col=1:21,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'p',pch=16,col=1:21,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',col=rainbow(21),cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',pch=16,col=rainbow(21),cex=2)
abline(h=0,v=0)
plot(x,y,type = 's',col=c('blue','green'))
abline(h=0,v=0)
plot(x,y,type = 'h',col=c('blue','green','red'))
abline(h=0,v=0)
plot(x,y,type = 'h',col=heat.colors(21),lwd=5)
abline(h=0,v=0)
############################################
par(mfrow=c(2,4))
plot(x,y,type = 'l',col=1:21)
abline(h=0,v=0)
plot(x,y,type = 'p',col=1:21,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'p',pch=16,col=1:21,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',col=rainbow(21),cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',pch=16,col=rainbow(21),cex=2)
abline(h=0,v=0)
plot(x,y,type = 's',col=c('blue','green'))
abline(h=0,v=0)
plot(x,y,type = 'h',col=c('blue','green','red'))
abline(h=0,v=0)
plot(x,y,type = 'h',col=heat.colors(21),lwd=5)
abline(h=0,v=0)
############################################
par(mfrow=c(2,4),mar=c(5,4,0.5,0.5))
plot(x,y,type = 'l',col=1:21)
abline(h=0,v=0)
plot(x,y,type = 'p',col=1:21,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'p',pch=16,col=1:21,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',col=rainbow(21),cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',pch=16,col=rainbow(21),cex=2)
abline(h=0,v=0)
plot(x,y,type = 's',col=c('blue','green'))
abline(h=0,v=0)
plot(x,y,type = 'h',col=c('blue','green','red'))
abline(h=0,v=0)
plot(x,y,type = 'h',col=heat.colors(21),lwd=5)
abline(h=0,v=0)
