x <- -10:10
y <- x^3  #### valores**2
plot(x,y,type = 'l',col=2)
abline(h=0,v=0)
plot(x,y,type = 'p',col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'p',pch=16,col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',pch=16,col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 's',col=2)
abline(h=0,v=0)
plot(x,y,type = 'h',col=2)
abline(h=0,v=0)
plot(x,y,type = 'n',col=2)
abline(h=0,v=0)
############################################
par(mfrow=c(2,4))
plot(x,y,type = 'l',col=2)
abline(h=0,v=0)
plot(x,y,type = 'p',col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'p',pch=16,col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',pch=16,col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 's',col=2)
abline(h=0,v=0)
plot(x,y,type = 'h',col=2)
abline(h=0,v=0)
plot(x,y,type = 'n',col=2)
abline(h=0,v=0)
############################################
par(mfrow=c(2,4),mar=c(5,4,0.5,0.5))
plot(x,y,type = 'l',col=2)
abline(h=0,v=0)
plot(x,y,type = 'p',col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'p',pch=16,col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 'o',pch=16,col=2,cex=2)
abline(h=0,v=0)
plot(x,y,type = 's',col=2)
abline(h=0,v=0)
plot(x,y,type = 'h',col=2)
abline(h=0,v=0)
plot(x,y,type = 'n',col=2)
abline(h=0,v=0)

